Repository if-mentor/next_todo_12, pull requests merged in 2023-11, with the labels that each got.

#7 vscodeの設定
  .vscode/settings.json
Labels: vscode

#15 Top markup
  doc/rule.md
  src/app/top/page.tsx
Labels: markup

#18 login画面のマークアップ
  src/app/login/page.tsx
Labels: markup

#22 Edit_マークアップ
  src/app/edit/page.tsx
  src/app/not-found.tsx
Labels: markup

#23 vscode 設定ファイル 修正
  .vscode/settings.json
Labels: fix

#24 Top markup2
  src/app/top/page.tsx
Labels: markup

#33 Feature/show
  src/app/show/page.tsx
Labels: feature

#21 Markup show
  src/app/show/page.tsx
Labels: markup

#26 Not found_マークアップ
  src/app/create/page.tsx
  src/app/not-found.tsx
Labels: markup

#30 top機能
  src/app/edit/[id]/page.tsx
  src/app/top/page.tsx
Labels: feature

#31 Create機能
  src/app/create/page.tsx
Labels: feature
